# Generated by Django 2.2.28 on 2024-02-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20240205_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
    ]
